# This is a basic workflow to help you get started with Actions

name: CI Gatsby Ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'https://epic-einstein-d54c6c.netlify.com'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
